name: Create Releases And Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - name: Create GitHub release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: ''
          draft: false
          prerelease: false

  build-gnu:
    needs: create-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu,aarch64-unknown-linux-gnu
          components: rustfmt,clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "release-build-gnu"
          cache-on-failure: true

      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libevdev-dev \
            pkg-config \
            gcc-aarch64-linux-gnu

      - name: Build and test GNU targets
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true
          RUSTFLAGS: "-C opt-level=3 -C embed-bitcode=yes"
        run: |
          # Run tests on native target
          cargo test --verbose --release --all-features --jobs $(nproc)
          
          # Build GNU targets
          cargo build --verbose --release --target x86_64-unknown-linux-gnu --jobs $(nproc)
          cargo build --verbose --release --target aarch64-unknown-linux-gnu --jobs $(nproc) --config target.aarch64-unknown-linux-gnu.linker=\"aarch64-linux-gnu-gcc\"

      - name: Strip binaries
        run: |
          strip target/x86_64-unknown-linux-gnu/release/evremap
          aarch64-linux-gnu-strip target/aarch64-unknown-linux-gnu/release/evremap

      - name: Upload GNU binaries
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: target/x86_64-unknown-linux-gnu/release/evremap
          asset_name: evremap-x86_64-unknown-linux-gnu
          asset_content_type: application/octet-stream

      - name: Upload aarch64 GNU binary
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: target/aarch64-unknown-linux-gnu/release/evremap
          asset_name: evremap-aarch64-unknown-linux-gnu
          asset_content_type: application/octet-stream

  build-musl:
    needs: create-release
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    permissions:
      contents: write
    steps:
      - name: Install build dependencies
        run: |
          apk add --no-cache \
            build-base \
            cargo \
            git \
            linux-headers \
            libevdev-dev \
            pkgconfig \
            aarch64-linux-musl-gcc

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl,aarch64-unknown-linux-musl
          components: rustfmt,clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "release-build-musl"
          cache-on-failure: true

      - name: Build MUSL targets
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true
          RUSTFLAGS: "-C opt-level=3 -C embed-bitcode=yes"
        run: |
          # Build MUSL targets
          cargo build --verbose --release --target x86_64-unknown-linux-musl --jobs $(nproc)
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-musl-gcc \
          cargo build --verbose --release --target aarch64-unknown-linux-musl --jobs $(nproc)

      - name: Strip binaries
        run: |
          strip target/x86_64-unknown-linux-musl/release/evremap
          aarch64-linux-musl-strip target/aarch64-unknown-linux-musl/release/evremap

      - name: Upload x86_64 MUSL binary
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: target/x86_64-unknown-linux-musl/release/evremap
          asset_name: evremap-x86_64-unknown-linux-musl
          asset_content_type: application/octet-stream

      - name: Upload aarch64 MUSL binary
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: target/aarch64-unknown-linux-musl/release/evremap
          asset_name: evremap-aarch64-unknown-linux-musl
          asset_content_type: application/octet-stream

  create-source-archives:
    needs: create-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create source archives
        run: |
          mkdir -p target/source
          git archive --format=tar.gz -o target/source/evremap-${{ github.ref_name }}.tar.gz HEAD
          git archive --format=zip -o target/source/evremap-${{ github.ref_name }}.zip HEAD

      - name: Upload source archives
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: target/source/evremap-${{ github.ref_name }}.tar.gz
          asset_name: evremap-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload zip archive
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: target/source/evremap-${{ github.ref_name }}.zip
          asset_name: evremap-${{ github.ref_name }}.zip
          asset_content_type: application/zip
